name: CI for Monorepo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm build

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm run test # or prisma generate, lint, etc.
